[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.0", features = ["derive"] }
aya-tool = { git = "https://github.com/aya-rs/aya", branch = "main" }
tempfile = "3.3"
phf = { version = "0.11", features = ["macros"] }
