version: '3.8'

services:
  wireguard_server:
    build: .
    image: wireguard-test:latest
    volumes:
      - ../target/debug/examples/logger-firewall:/logger-firewall
      - ./peers/:/config/:rw
    environment:
      - PEERS=3
      - SERVERURL=172.8.0.2
      - LOG_CONFS=false
      - PUID=1000
      - PGID=1000
      - RUST_LOG=trace
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    # Not sure what capabilities are required to create eBPF maps
    privileged: true
    networks:
      internal:
        ipv4_address: 172.8.0.2
    command: /logger-firewall --iface wg0

  peer1:
    image: wireguard-test:latest
    volumes:
      - ./peers/peer1/peer1.conf:/config/wg0.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      internal:
        ipv4_address: 172.8.0.3
    command: /bin/sh -c "sleep 10 && echo peer1! && echo howdy | nc -nvvv fafa::3 5500"

  peer2:
    image: wireguard-test:latest
    volumes:
      - ./peers/peer2/peer2.conf:/config/wg0.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      internal:
        ipv4_address: 172.8.0.4
    command: /bin/sh -c "sleep 5 && echo peer2! && while true; do echo "hi" | nc -nlvvv fafa::3 5500; done"

  peer3:
    image: wireguard-test:latest
    volumes:
      - ./peers/peer3/peer3.conf:/config/wg0.conf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      internal:
        ipv4_address: 172.8.0.5
    command: /bin/sh -c "sleep 5 && echo peer3! && ping 142.251.134.78"

networks:
  internal:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.8.0.0/16
        - subnet: 2005:3990:3990::/64