name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        kernel_version: [4.18, 5.4, 5.10, 5.15]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rust-src
      - name: Cache cargo modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-18.04-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-18.04-cargo
      - name: Install bpf-linker
        working-directory: ./userspace
        run: cargo install bpf-linker
      - name: Build
        working-directory: ./userspace
        run: cargo build --verbose --example ci-run --release
      - name: Run tests
        working-directory: ./userspace
        run: cargo test --verbose
      - name: Run clippy
        working-directory: ./userspace
        run: cargo +nightly clippy -- -D clippy::all
      - name: Test on kernel
        run: cargo xtask run-on ${{ matrix.kernel_version }}  --release
