name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          # TODO: Not sure why rust-src is needed
          components: clippy, rust-src
      - name: Install bpf-linker
        run: cargo install bpf-linker
      - name: Build Ebpf
        run: cargo xtask build-ebpf
      - name: Build
        run: cargo build --verbose --example logger-firewall
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: logger-firewall
          path: target/debug/examples/logger-firewall
