name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          # TODO: Not sure why rust-src is needed
          components: clippy, rust-src
      - name: Build Ebpf
        run: cargo xtask build-ebpf
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
